services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Dashboard (Opcional expor)
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      # Definindo os pontos de entrada
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Redirecionamento Automático para HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Configuração do Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-seu-email-real@exemplo.com}"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json" # Persistência dos certificados
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    external: true
